# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# encoding: utf-8
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'emmajouffroypro@gmail.com', password: 'emmajou', password_confirmation: 'emmajou')
AdminUser.create!(email: 'noemilamane2@gmail.com', password: 'noemil', password_confirmation: 'noemil')
AdminUser.create!(email: 'eliemargoet@gmail.com', password: 'eliem', password_confirmation: 'eliem')
AdminUser.create!(email: 'fleurgriffon@gmail.com', password: 'fleurg', password_confirmation: 'fleurg')
AdminUser.create!(email: 'florianlaville33@gmail.com', password: 'florian', password_confirmation: 'florian')
AdminUser.create!(email: 'margauxdelafontaine@gmail.com', password: 'margaux', password_confirmation: 'margaux')
AdminUser.create!(email: 'swann.latasa@gmail.com', password: 'swannl', password_confirmation: 'swannl')
AdminUser.create!(email: 'lafon_aurelien@orange.fr', password: 'aurelien', password_confirmation: 'aurelien')


not1 = Notion.create!(name:"vie", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/vie.jpg"),:notion_id =>  1)
not2 = Notion.create!(name:"âge", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/age.jpg"),:notion_id => 2)
not3 = Notion.create!(name:"mort", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/mort.jpg"),:notion_id => 3
not4 = Notion.create!(name:"alimentation", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/alimentation.jpg"),:notion_id => 4)
not5 = Notion.create!(name:"aliment", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/aliment.jpg"),:notion_id => 5)
not6 = Notion.create!(name:"jeu", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/jeu.jpg"),:notion_id => 6)
not7 = Notion.create!(name:"sport", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/sport.jpg"),:notion_id => 7)
not8 = Notion.create!(name:"commerce", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/commerce.jpg"),:notion_id => 8)
not9 = Notion.create!(name:"argent", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/argent.jpg"),:notion_id => 9)
not10 = Notion.create!(name:"économie", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/economie.jpg"),:notion_id => 10)
not11 = Notion.create!(name:"entreprise", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/entreprise.jpg"),:notion_id => 11)
not12 = Notion.create!(name:"possession", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/possession.jpg"),:notion_id => 12)
not13 = Notion.create!(name:"communication", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/communication.jpg"),:notion_id => 13)
not14 = Notion.create!(name:"langage", :photo =>  File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/langage.jpg"),:notion_id => 14)
not15 = Notion.create!(name:"écriture", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/ecriture.jpg"),:notion_id => 15)
not16 = Notion.create!(name:"informer", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/informer.jpg"),:notion_id => 16)
not17 = Notion.create!(name:"télécommunication", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/telecommunication.jpg"),:notion_id => 17)
not18 = Notion.create!(name:"internet", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/internet.jpg"),:notion_id => 18)
not19 = Notion.create!(name:"nom", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/nom.jpg"),:notion_id => 19)
not20 = Notion.create!(name:"mouvement", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/mouvement.jpg"),:notion_id => 20)
not21 = Notion.create!(name:"déplacement", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/deplacement.jpg"),:notion_id => 21)
not22 = Notion.create!(name:"transport", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/transport.jpg"),:notion_id => 22)
not23 = Notion.create!(name:"bateau", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/bateau.jpg"),:notion_id => 23)
not24 = Notion.create!(name:"automobile", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/automobile.jpg"),:notion_id => 24)
not25 = Notion.create!(name:"train", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/train.jpg"),:notion_id => 25)
not26 = Notion.create!(name:"avion", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/avion.jpg"),:notion_id => 26)
not27 = Notion.create!(name:"deux-roues", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/deuxroues.jpg"),:notion_id => 27)
not28 = Notion.create!(name:"corps", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/corps.jpg"),:notion_id => 28)
not29 = Notion.create!(name:"organe", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/organe.jpg"),:notion_id => 29)
not30 = Notion.create!(name:"santé", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/sante.jpg"),:notion_id => 30)
not31 = Notion.create!(name:"hygiène", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/hygiene.jpg"),:notion_id => 31)
not32 = Notion.create!(name:"sommeil", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/sommeil.jpg"),:notion_id => 32)
not33 = Notion.create!(name:"position", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/position.jpg"),:notion_id => 33)
not34 = Notion.create!(name:"sexualité", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/sexualite.jpg"),:notion_id => 34)
not35 = Notion.create!(name:"technique", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/technique.jpg"),:notion_id => 35)
not36 = Notion.create!(name:"instrument", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/instrument.jpg"),:notion_id => 36)
not37 = Notion.create!(name:"ordinateurs", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/ordinateurs.jpg"),:notion_id => 37)
not38 = Notion.create!(name:"Animal", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/animal.jpg"),:notion_id => 38)
not39 = Notion.create!(name:"Invertébré", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/invertebre.jpg"),:notion_id => 39)
not40 = Notion.create!(name:"Vertébré", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/vertebre.jpg"),:notion_id => 40)
not41 = Notion.create!(name:"Plante", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/plante.jpg"),:notion_id => 41)
not42 = Notion.create!(name:"Pouvoir", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/pouvoir.jpg"),:notion_id => 42)
not43 = Notion.create!(name:"Politique", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/politique.jpg"),:notion_id => 43)
not44 = Notion.create!(name:"Pays", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/pays.jpg"),:notion_id => 44)
not45 = Notion.create!(name:"Justice", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/justice.jpg"),:notion_id => 45)
not46 = Notion.create!(name:"Sécurité", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/securite.jpg"),:notion_id => 46)
not47 = Notion.create!(name:"Militaire", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/militaire.jpg"),:notion_id => 47)
not48 = Notion.create!(name:"Famille", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/famille.jpg"),:notion_id => 48)
not49 = Notion.create!(name:"Mariage", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/mariage.jpg"),:notion_id => 49)
not50 = Notion.create!(name:"Matière", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/matiere.jpg"),:notion_id => 50)
not51 = Notion.create!(name:"Atome", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/atome.jpg"),:notion_id => 51)
not52 = Notion.create!(name:"Déchet", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/dechet.jpg"),:notion_id => 52)
not53 = Notion.create!(name:"Feu", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/feu.jpg"),:notion_id => 53)
not54 = Notion.create!(name:"Eau", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/eau.jpg"),:notion_id => 54)
not55 = Notion.create!(name:"Force", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/force.jpg"),:notion_id => 55)
not56 = Notion.create!(name:"Edifice", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/edifice.jpg"),:notion_id => 56)
not57 = Notion.create!(name:"Ville", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/ville.jpg"),:notion_id => 57)
not58 = Notion.create!(name:"Voie", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/voie.jpg"),:notion_id => 58)
not59 = Notion.create!(name:"Espace", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/espace.jpg"),:notion_id => 59)
not60 = Notion.create!(name:"Orientation", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/orientation.jpg"),:notion_id => 60)
not61 = Notion.create!(name:"Distance", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/distance.jpg"),:notion_id => 61)
not62 = Notion.create!(name:"Univers", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/univers.jpg"),:notion_id => 62)
not63 = Notion.create!(name:"Terre", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/terre.jpg"),:notion_id => 63)
not64 = Notion.create!(name:"Mer", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/mer.jpg"),:notion_id => 64)
not65 = Notion.create!(name:"Continent", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/continent.jpg"),:notion_id => 65)
not66 = Notion.create!(name:"Climat", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/climat.jpg"),:notion_id => 66)
not67 = Notion.create!(name:"Saison", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/saison.jpg"),:notion_id => 67)
not68 = Notion.create!(name:"Temps", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/temps.jpg"),:notion_id => 68)
not69 = Notion.create!(name:"Date-Calendrier", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/calendrier.jpg"),:notion_id => 69)
not70 = Notion.create!(name:"Fait", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/fait.jpg"),:notion_id => 70)
not71 = Notion.create!(name:"Intellect", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/intellect.jpg"),:notion_id => 71)
not72 = Notion.create!(name:"Savoir", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/savoir.jpg"),:notion_id => 72)
not73 = Notion.create!(name:"Apprentissage", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/apprentissage.jpg"),:notion_id => 73)
not74 = Notion.create!(name:"Sens", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/sens.jpg"),:notion_id => 74)
not75 = Notion.create!(name:"Oui-Non", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/ouinon.jpg"),:notion_id => 75)
not76 = Notion.create!(name:"Verité", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/verite.jpg"),:notion_id => 76)
not77 = Notion.create!(name:"Société", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/societe.jpg"),:notion_id => 77)
not78 = Notion.create!(name:"Fête", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/fete.jpg"),:notion_id => 78)
not79 = Notion.create!(name:"Esprit", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/esprit.jpg"),:notion_id => 79)
not80 = Notion.create!(name:"Religion", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/religion.jpg"),:notion_id => 80)
not81 = Notion.create!(name:"Nombre", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/nom.jpg"),:notion_id => 81)
not82 = Notion.create!(name:"Mesure", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/mesure.jpg"),:notion_id => 82)
not83 = Notion.create!(name:"Dimension", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/dimension.jpg"),:notion_id => 83)
not84 = Notion.create!(name:"Sentiment", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/sentiment.jpg"),:notion_id => 84)
not85 = Notion.create!(name:"Salutation", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/salutation.jpg"),:notion_id => 85)
not86 = Notion.create!(name:"Faire", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/faire.jpg"),:notion_id => 86)
not87 = Notion.create!(name:"Finalité", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/finalite.jpg"),:notion_id => 87)
not88 = Notion.create!(name:"Travail", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/travail.jpg"),:notion_id => 88)
not89 = Notion.create!(name:"Agriculture", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/agriculture.jpg"),:notion_id => 89)
not90 = Notion.create!(name:"Industrie", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/industrie.jpg"),:notion_id => 90)
not91 = Notion.create!(name:"Vision", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/vision.jpg"),:notion_id => 91)
not92 = Notion.create!(name:"Audition", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/audition.jpg"),:notion_id => 92)
not93 = Notion.create!(name:"Toucher", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/toucher.jpg"),:notion_id => 93)
not94 = Notion.create!(name:"Être humain", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/etrehumain.jpg"),:notion_id => 94)
not95 = Notion.create!(name:"Soi", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/soi.jpg"),:notion_id => 95)
not96 = Notion.create!(name:"Objet", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/objet.jpg"),:notion_id => 96)
not97 = Notion.create!(name:"Textile", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/textile.jpg"),:notion_id => 97)
not98 = Notion.create!(name:"Art", :photo => File.new(__dir__+" /Users/jouffroy/Desktop/notions/vignette/art.jpg"),:notion_id => 98)
